---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "1.0.1"
    name: java
  - src: git@github.com:Ecriptor/elastic-role.git
    scm: git
    version: "1.0.2"
    name: elastic
  - src: git@github.com:Ecriptor/kibana-role.git
    scm: git
    version: "1.0.1"
    name: kibana
